services:
  - type: web
    name: snapautism-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://snapautism-backendd.onrender.com
